# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go
Version:                1.1.0
%global tag             sdk/security/keyvault/azkeys/v1.1.0

%gometa -f

%global common_description %{expand:
This repository is for active development of the Azure SDK for Go. For
consumers of the SDK we recommend visiting our public developer docs at:.}

%global golicenses      sdk/security/keyvault/azkeys/LICENSE.txt
%global godocs          sdk/security/keyvault/azkeys/CHANGELOG.md\\\
                        sdk/security/keyvault/azkeys/README.md\\\
                        sdk/security/keyvault/azkeys/TROUBLESHOOTING.md\\\
                        sdk/security/keyvault/azkeys/autorest.md

Name:           golang-github-azure-sdk-security-keyvault-azkeys
Release:        %autorelease
Summary:        This repository is for active development of the Azure SDK for Go. For consumers of the SDK we recommend visiting our public developer docs at:

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in eng/tools/apidiff eng/tools/deprecate eng/tools/doccheck eng/tools/generator eng/tools/indexer eng/tools/mgmtreport eng/tools/pkgchk eng/tools/profileBuilder eng/tools/smoketests sdk/samples/azidentity/manual-tests/managed-identity/functions sdk/samples/azidentity/manual-tests/managed-identity/general sdk/samples/azidentity/manual-tests/managed-identity/service-fabric; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license sdk/security/keyvault/azkeys/LICENSE.txt
%doc sdk/security/keyvault/azkeys/CHANGELOG.md
%doc sdk/security/keyvault/azkeys/README.md
%doc sdk/security/keyvault/azkeys/TROUBLESHOOTING.md
%doc sdk/security/keyvault/azkeys/autorest.md
#%%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
