# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/containers/common
%global goipath         github.com/containers/common
Version:                0.60.2

%gometa -f

%global common_description %{expand:
Location for shared common files in github.com/containers repos.}

%global golicenses      LICENSE pkg/report/camelcase/LICENSE.md
%global godocs          docs README.md

Name:           golang-github-containers-common
Release:        %autorelease
Summary:        Location for shared common files in github.com/containers repos

License:        MIT AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in libnetwork/netavark/testplugin pkg/seccomp; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE pkg/report/camelcase/LICENSE.md
%doc docs README.md
#%%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
