# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/florianl/go-tc
%global goipath         github.com/florianl/go-tc
Version:                0.4.4

%gometa -f

%global common_description %{expand:
Traffic control in pure go - it allows to read and alter queues, filters and
classes.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-florianl-tc
Release:        %autorelease
Summary:        Traffic control in pure go - it allows to read and alter queues, filters and classes

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
