# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/giantswarm/microerror
%global goipath         github.com/giantswarm/microerror
Version:                0.4.1

%gometa -f

%global common_description %{expand:
Go library to facilitate error handling, based on juju/errgo (deprecated).}

%global golicenses      LICENSE
%global godocs          CREADME.md

Name:           golang-github-giantswarm-microerror
Release:        %autorelease
Summary:        Go library to facilitate error handling, based on juju/errgo (deprecated)

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
