# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/inspektor-gadget/inspektor-gadget
%global goipath         github.com/inspektor-gadget/inspektor-gadget
Version:                v0.30.0
%global tag             v0.30.0

%gometa -f

%global common_description %{expand:
The eBPF tool and systems inspection framework for Kubernetes, containers and
Linux hosts.}

%global golicenses      LICENSE LICENSE-bpf.txt
%global godocs          README.md

Name:           golang-github-inspektor-gadget
Release:        %autorelease
Summary:        The eBPF tool and systems inspection framework for Kubernetes, containers and Linux hosts

License:        GPL-2.0-only AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in gadget-container/cleanup gadget-container/entrypoint gadget-container/gadgettracermanager gadget-container/hooks/nri gadget-container/hooks/oci gadgets/trace_exec gadgets/trace_mount gadgets/trace_open integration/ig/non-k8s integration/k8s pkg/gadgets/trace/tcpdrop/tracer/dropreasongen tools/check-readme tools/dnstester tools/eks-cleanup tools/testjson2md; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE LICENSE-bpf.txt
%doc README.md
#%%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
