# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/bradleyfalzon/ghinstallation
%global goipath         github.com/bradleyfalzon/ghinstallation
Version:                2.11.0
Version:                v2.11.0
%global tag             v2.11.0

%gometa -f

%global common_description %{expand:
HTTP Round Tripper for GitHub Apps - Authenticate as an Installation Workflow.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md

Name:           golang-github-bradleyfalzon-ghinstallation
Release:        %autorelease
Summary:        HTTP Round Tripper for GitHub Apps - Authenticate as an Installation Workflow

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
