# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/google/go-github
%global goipath         github.com/google/go-github
Version:                53.0.0
%global tag             v53.0.0

%gometa -f

%global common_description %{expand:
Go library for accessing the GitHub v3 API.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-google
Release:        %autorelease
Summary:        Go library for accessing the GitHub v3 API

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in github update-urls; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE github/licenses.go github/licenses_test.go
%doc example AUTHORS CONTRIBUTING.md README.md example scrape/README.md
# %%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
